version: '3.4'
services:
    sut:
        container_name: {{cookiecutter.syncpack_name}}_test
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: test
        image: is_{{cookiecutter.syncpack_name}}:unit-test
        command: tox
